# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 17:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smalljobsapp', '0005_purchase_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smalljobsapp.Gig')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='status',
        ),
        migrations.AddField(
            model_name='purchase',
            name='transaction_id',
            field=models.CharField(default='transaction.id', max_length=100),
        ),
    ]
