# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smalljobsapp', '0006_auto_20160822_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedpurchase',
            name='orde_id',
            field=models.CharField(default='order_id', max_length=100),
        ),
        migrations.AddField(
            model_name='purchase',
            name='orde_id',
            field=models.CharField(default='order_id', max_length=100),
        ),
    ]
