# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smalljobsapp', '0007_auto_20160822_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='failedpurchase',
            old_name='orde_id',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='orde_id',
            new_name='order_id',
        ),
    ]
