# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smalljobsapp', '0008_auto_20160822_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failedpurchase',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='failedpurchase',
            name='gig',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='order_id',
        ),
        migrations.DeleteModel(
            name='FailedPurchase',
        ),
    ]
